### ISSUE TITLE
case parsing

### ISSUE THREAD

**Issue by neochrome** [pugjs/jade#2235]
Hi,
I run into problems parsing this kind of case/when
```jade
case "a:b"
  when "a:b"
    p a:b
  default
    p default
```
The error is `expected "indent", but got "filter"`, but really it should handle `"a:b"` as a string literal - right?

This work around is a bit of a kludge, but at least it works:
```jade
-var test = "a:b";
case "a:b"
  when test
    p a:b
  default
    p default
```

**Comment by ForbesLindesay** [comment]
Someone needs to check if this can be reproduced on the latest lexer/parser and add a test case to github.com/pugjs/pug-lexer

**Comment by TimothyGu** [comment]
lexer reports this error:

```
Error: Pug:2:12
    1| case "a:b"
  > 2|   when "a:b"
------------------^
    3|     p a:b
    4|   default
    5|     p default

unexpected text ""
   "
    at makeError (/home/timothy_gu/pug/pug-error/index.js:32:13)
    at Lexer.error (/home/timothy_gu/pug/pug-lexer/index.js:52:15)
    at Lexer.fail (/home/timothy_gu/pug/pug-lexer/index.js:1254:10)
    at Lexer.advance (/home/timothy_gu/pug/pug-lexer/index.js:1314:15)
    at Lexer.callLexerFunction (/home/timothy_gu/pug/pug-lexer/index.js:1269:23)
    at Lexer.getTokens (/home/timothy_gu/pug/pug-lexer/index.js:1325:12)
    at lex (/home/timothy_gu/pug/pug-lexer/index.js:12:42)
    at repl:1:13
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
```

Closing. See pugjs/pug-lexer#57 instead.
