### ISSUE TITLE
Failure to parse inline tags

### ISSUE THREAD

**Issue by azdavis** [pugjs/jade#2247]
Here's a quick test I whipped up:

```jade
doctype html
html
  head
    title test
  body.
    #[span private/]
```

This fails with the following error:

```
Error: index.jade:7
    5|   body.
    6|     #[span private/]
  > 7|

The end of the string was reached with no closing bracket found.
    at parseMax (/[REDACTED]/node_modules/character-parser/index.js:26:13)
    at Parser.parseInlineTagsInText (/[REDACTED]/node_modules/jade/lib/parser.js:688:21)
    at Parser.<anonymous> (/[REDACTED]/node_modules/jade/lib/parser.js:711:38)
    at Array.reduce (native)
    at Parser.parseTextBlock (/[REDACTED]/node_modules/jade/lib/parser.js:710:28)
    at Parser.tag (/[REDACTED]/node_modules/jade/lib/parser.js:836:24)
    at Parser.parseTag (/[REDACTED]/node_modules/jade/lib/parser.js:759:17)
    at Parser.parseExpr (/[REDACTED]/node_modules/jade/lib/parser.js:211:21)
    at Parser.block (/[REDACTED]/node_modules/jade/lib/parser.js:729:25)
    at Parser.tag (/[REDACTED]/node_modules/jade/lib/parser.js:838:24)
```

This error seems to happen whenever there's an inline tag whose inner HTML begins with the word `private/`, `public/`, or `protected/`.

**Comment by TimothyGu** [comment]
This is fixed in master.

**Comment by azdavis** [comment]
Thanks! Maybe this isn't the type of question one can/should ask, but is there a timetable for the next release?

**Comment by TimothyGu** [comment]
It was actually planned for December last year but you can see how that turned out :)

But more seriously, it depends on the availability of @ForbesLindesay, who unfortunately is still the sole owner of some crucial npm packages (for instance, `pug`) so I am not able to make the release myself.
